[package]
name = "cargo-depcheck"
version = "0.1.0"
edition = "2024"

[dependencies]
anstream = "0.6"
anstyle = "1"
cargo-lock = "11"
clap = { version = "4", features = ["derive"] }
clap-cargo = { version = "0.18", features = ["clap"] }
indexmap = "2"
